spring:
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  cache: false
 datasource:
  alipay-db:
   name: alipay-db
   jdbc-url: jdbc:mysql://localhost:3306/Ali_Java_PTA_AliPay?characterEncoding=utf-8
   url: jdbc:mysql://localhost:3306/Ali_Java_PTA_AliPay?characterEncoding=utf-8
   username: root
   password: Jintopno1$$$
   driver-class-name: com.mysql.cj.jdbc.Driver
   type: com.alibaba.druid.pool.xa.DruidXADataSource
  bank-db:
   name: bank-db
   url: jdbc:mysql://localhost:3306/Ali_Java_PTA_Bank?characterEncoding=utf-8
   jdbc-url: jdbc:mysql://localhost:3306/Ali_Java_PTA_Bank?characterEncoding=utf-8
   username: root
   password: Jintopno1$$$
   driver-class-name: com.mysql.cj.jdbc.Driver
   type: com.alibaba.druid.pool.xa.DruidXADataSource
  my-db:
   #  数据源基本配置
   name: my-db
   username: root
   password: Jintopno1$$$
   jdbc-url: jdbc:mysql://localhost:3306/Ali_Java_PTA?characterEncoding=utf-8
   url: jdbc:mysql://localhost:3306/Ali_Java_PTA?characterEncoding=utf-8
   driver-class-name: com.mysql.cj.jdbc.Driver
   type: com.alibaba.druid.pool.xa.DruidXADataSource
 redis:
  cluster:
   max-redirects: 1
   nodes: 127.0.0.1:8000,127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004,127.0.0.1:8005
   timeout: 6000ms # 连接池超时时间（毫秒）
  database: 0
  #  host: 127.0.0.1
  #  port: 6379
  password: # 如果未单独配置默认为空即可
  timeout: 1000
  jedis:
   pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
mybatis:
 mapper-locations: classpath*:mapper/*Mapper.xml
 level:
  com.example.alijavapta.mapper: trace # 改成你的mapper文件所在包路径
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
 port: 8080
shiro:
 sessionManager:
  sessionIdCookieEnabled: true
  sessionIdUrlRewritingEnabled: true
 unauthorizedUrl: /unauthorizedUrl
 web:
  enabled: true
 successUrl: /index
 loginUrl: /login

